version: "3.3"
services:
  app:
    build: .
    volumes:
      - ./conf/key.php:/var/www/html/lib/php/key.php
    depends_on:
      - db
    ports:
      - 8081:80
  db:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: somepassword
      MYSQL_DATABASE: velobs
      MYSQL_USER: velobs
      MYSQL_PASSWORD: velobs

volumes:
  dbdata:
